on: [push]

jobs:
 custom_markdown_rules:
    runs-on: ubuntu-latest
    name: Markdown Rules Check
    steps:
      - uses: actions/checkout@v3
        with:
         fetch-depth: "0"
      - name: Markdown Rules Check String step
        id: selftest
        uses: hirenp-waferwire/custom-markdown-action@main
        with:
          GlobPath: 'Test/**/*.md'
